### PR TITLE
created home page and added bottom navigation bar

### LINKED ISSUE #7: Create home page and add bottom navigation bar with 4 tabs
onclick login route to this page 

Create 4 empty screens for this page 

1)Dashboard 
2)Wallet
3)Notifications
4)Profile

### PR DESCRIPTION
**Pull request by diksha-mobile-dev**
closes #7

### CODE REVIEW

**Comment by santhosh-mobile-dev** [comment]
Don’t write scaffold in build .. this is how I did the login ??

**Comment by santhosh-mobile-dev** [comment]
Create generic bottom navigation bar item and use it

**Comment by santhosh-mobile-dev** [comment]
@darshanaAeione dont merge it until I approve

**Review by santhosh-mobile-dev — CHANGES_REQUESTED** [review]
See the comments and make changes accordingly

**Review by darshanaAeione — APPROVED** [review]

**Pull request merged**
